#!/bin/bash
gcc codifica.c -o codifica
gcc canal.c -o canal
gcc decodifica.c -o decodifica
#./codifica textoPrueba
#./codifica textoPrueba | ./canal 100
./codifica textoPrueba | ./canal 100 | ./decodifica
#./decodifica
#echo hi