#!/bin/bash
gcc codifica.c -o codifica
gcc canal.c -o canal
gcc decodifica.c -o decodifica
#./codifica entrada.txt
#./codifica entrada.txt | ./canal 100
#./codifica entrada.txt | ./canal 100 | ./decodifica 
./codifica pursuit-evasion.pdf | ./canal 100 | ./decodifica
#./decodifica
gcc estadisticos.c -o estadisticos
./estadisticos VectoresCodificados.txt VectoresRecibidos.txt VectoresDecodificados.txt